<?php
//Modulo BASES: Este modulo concentra todas las funcionalidades relacionadas a la gestion y administraión de los datos correspondientes a los diferentes programas que se ejecutan desde la SES

include 'includes/gestionar_socios.inc';
include 'includes/socio.inc';
include 'includes/data_access.inc';
include 'includes/estado_socio.inc';
include 'includes/datos_socio.inc';
include 'includes/gestionar_categorias_socio.inc';
include 'includes/categoria.inc';
include 'includes/gestionar_estados_socio.inc';
include 'includes/estado.inc';
include 'includes/gestionar_tipo_grupo_familiar.inc';
include 'includes/tipo_grupo_familiar.inc';
include 'includes/registrar_pago.inc';
include 'includes/registrar_pagos_cod_barra.inc';
include 'includes/generar_cupones.inc';
include 'includes/adjuntar_foto.inc';
include 'includes/ingreso_socio.inc';
include 'includes/cobranza_socio.inc';
include 'includes/plan_pago_socio.inc';
include 'includes/test.inc';
include 'includes/imprimir_cuenta_socio.inc';
include 'includes/generar_liquidacion.inc';
include 'includes/gestionar_recibos.inc';

function socios_init(){
   drupal_add_js(array('custom' => array('generar_liquidacion' => url('socios/generar_liquidacion_ajax'))), 'setting');
   drupal_add_js(drupal_get_path('module', 'socios') . '/js/generar_liquidacion.js');

}

function socios_permission(){


  return array(
  	'acceso a gestionar socios' =>  array(
		'title' => t('Gestion de socios'),
		'description' => t('Permisos para acceder a la gestion del socio.'),
	),
	'acceso a gestionar socio' =>  array(
		'title' => t('Gestion de socios - Gestionar Socio'),
		'description' => t('Permisos para acceder a la gestion de un socio en particular.'),
	),
	'acceso a cambiar estado del socio' =>  array(
		'title' => t('Gestion de socios - Cambiar Estado del Socio'),
		'description' => t('Permisos para acceder a cambiar el estado de un socio.'),
	),
	'acceso a datos del socios' =>  array(
		'title' => t('Gestion de socios - Ver Datos del Socio'),
		'description' => t('Permisos para acceder a ver datos del socio.'),
	),
  'acceso a gestionar categorias del socio' =>  array(
    'title' => t('Gestion de socios - Gestionar Categorías'),
    'description' => t('Permisos para acceder a gestionar las categorías de socios.'),
  ),
  'acceso a gestionar una categoria del socio' =>  array(
    'title' => t('Gestion de socios - Categoria de socio'),
    'description' => t('Permisos para acceder a Alta, modificación y visualización de las categorías de socio.'),
  ),
  'acceso a gestionar estados del socio' =>  array(
    'title' => t('Gestion de socios - Gestionar Estados del socio'),
    'description' => t('Permisos para acceder a gestionar los estados de socio.'),
  ),
  'acceso a gestionar estado de socio' =>  array(
    'title' => t('Gestion de socios - Estado de socio'),
    'description' => t('Permisos para acceder a Alta, modificación y visualización de los estados de socio.'),
  ),
  'acceso a gestionar tipos de grupo familiar' =>  array(
    'title' => t('Gestion de socios - Gestionar tipos de grupo familiar'),
    'description' => t('Permisos para acceder a gestionar tipos de grupo familiar.'),
  ),
  'acceso a gestionar tipo de grupo familiar' =>  array(
    'title' => t('Gestion de socios - Tipo de grupo familiar'),
    'description' => t('Permisos para acceder a Alta, modificación y visualización de un tipo de grupo familiar.'),
  ),
  'acceso a registrar pagos por cod barras' =>  array(
    'title' => t('Gestion de socios - Registrar pagos por Codigo de Barras'),
    'description' => t('Permisos para acceder a registrar pagos de cuotas desde código de barras.'),
  ),
  'acceso a generar cupones' =>  array(
    'title' => t('Gestion de socios - Generar cupones'),
    'description' => t('Permisos para generar cupones de pago de cuota.'),
  ),
  'acceso a adjuntar foto' =>  array(
    'title' => t('Gestion de socios - Adjuntar foto'),
    'description' => t('Permisos para adjuntar foto de socio.'),
  ),
  'acceso a ingreso socios' =>  array(
    'title' => t('Gestion de socios - Control de Ingreso de Socios'),
    'description' => t('Permisos para acceder al Control de Ingresos de Socios.'),
  ),
  'acceso a gestion socio cobranza' =>  array(
    'title' => t('Gestion de socios - Buscar socio para gestion de cobranzas'),
    'description' => t('Permisos para acceder a buscar un socio para gestionar un socio para su cobranza.'),
  ),
  'acceso a generar plan de pago de un socio' =>  array(
    'title' => t('Gestion de socios - Plan de Pago de un socio'),
    'description' => t('Permisos para acceder al registro de un plan de pago de un socio.'),
  ),
  'acceso a imprimir cuenta socio' =>  array(
    'title' => t('Gestion de socios - Imprimir cuenta de socio'),
    'description' => t('Permisos para acceder a imprimir la cuenta pagada de un socio.'),
  ),
  'acceso a generar liquidacion mensual' =>  array(
    'title' => t('Gestion de socios - Generar Liquidación Mensual'),
    'description' => t('Permisos para acceder a generar la liquiacion mensual.'),
  ),
  'acceso a ingreso socio - socio' =>  array(
    'title' => t('Gestion de socios - Control de Ingreso de Socios - Ver datos del socio'),
    'description' => t('Permisos para acceder a ver los datos  del socio en el control de Ingresos de Socios.'),
  ),
  'acceso a recibos del socio' =>  array(
    'title' => t('Gestion de socios - Gestion Recibos de Socio'),
    'description' => t('Permisos para acceder a gestionar los recibos de un socio.'),
  ),
  'acceso a anular recibo' =>  array(
    'title' => t('Gestion de socios - Anular Recibos de Socio'),
    'description' => t('Permisos para acceder a anular un recibo de un socio.'),
  ),
  );
}

/**
* Implements hook_help()
*/

function socios_help($path, $arg){
  switch ($path) {
    case 'socios/manage':
      // Help text for the simple page registered for this path.
      return t('This section displays the list of Pages.');
  }
}

/**
* Implements hook_menu()
*/

function socios_menu()
{
  /*------ ITEMS DE MENU PARA GESTION FINANCIERA -------*/
  $items['socios/gestionar_socios'] = array(
    'title' => 'SOCIOS',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gestionar_socios_form'),
    'access arguments' => array('acceso a gestionar socios'),
    'expanded' => TRUE,
  );//gestionar_socios.inc

  $items['socios/datos_socio'] = array(
    'title' => 'SOCIOS',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('datos_socio_form'),
    'access arguments' => array('acceso a datos del socios'),
    'expanded' => TRUE,
  );//gestionar_socios.inc

  $items['socios/socio'] = array(
    'title' => 'SOCIO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('socio_form'),
    'access arguments' => array('acceso a gestionar socio'),
    'expanded' => TRUE,
  );//socios.inc

  $items['/estado_socio'] = array(
    'title' => 'ESTADO DEL SOCIO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('estado_socio_form'),
    'access arguments' => array('acceso a cambiar estado del socio'),
    'expanded' => TRUE,
  );//estado_socio.inc
   $items['titular/autocomplete'] = array(
      'title' => 'Autocomplete titular',
      'page callback' => '_titular_autocomplete',
      'access arguments' => array('use autocomplete'),  //or whatever permission makes sense
      'type' => MENU_CALLBACK
    );
  $items['socios/gestionar_categorias_socio'] = array(
    'title' => 'CATEGORIAS DEL SOCIO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gestionar_categorias_form'),
    'access arguments' => array('acceso a gestionar categorias del socio'),
    'expanded' => TRUE,
  );//gestionar_categorias_socio.inc
  $items['socios/categoria'] = array(
    'title' => 'CATEGORIA',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('categoria_form'),
    'access arguments' => array('acceso a gestionar una categoria del socio'),
    'expanded' => TRUE,
  );//categoria.inc
  $items['socios/gestionar_estados_socio'] = array(
    'title' => 'ESTADOS DEL SOCIO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gestionar_estados_socio_form'),
    'access arguments' => array('acceso a gestionar estados del socio'),
    'expanded' => TRUE,
  );//gestionar_estados_socio.inc
  $items['socios/estados_socio'] = array(
    'title' => 'ESTADO DE SOCIO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('estado_form'),
    'access arguments' => array('acceso a gestionar estado de socio'),
    'expanded' => TRUE,
  );//estado.inc
  $items['socios/gestionar_tipo_grupo_familiar'] = array(
    'title' => 'TIPOS DE GRUPO FAMILIAR',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gestionar_tipo_grupo_familiar_form'),
    'access arguments' => array('acceso a gestionar tipos de grupo familiar'),
    'expanded' => TRUE,
  );//gestionar_tipo_grupo_familiar.inc
  $items['socios/tipo_grupo_familiar'] = array(
    'title' => 'TIPO DE GRUPO FAMILIAR',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tipo_grupo_familiar_form'),
    'access arguments' => array('acceso a gestionar tipo de grupo familiar'),
    'expanded' => TRUE,
  );//tipo_grupo_familiar.inc
  $items['socios/registrar_pagos_cod_barra'] = array(
    'title' => 'REGISTRAR PAGOS',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('registrar_pagos_cod_barra_form'),
    'access arguments' => array('acceso a registrar pagos por cod barras'),
    'expanded' => TRUE,
  );//registrar_pagos_cod_barra.inc
  $items['socios/registrar_pago'] = array(
    'title' => 'REGISTRAR PAGOS',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('registrar_pagos_form'),
    'access arguments' => array('acceso a registrar pagos'),
    'expanded' => TRUE,
  );//registrar_pago.inc
  $items['socios/generar_cupones'] = array(
    'title' => 'REGISTRAR PAGOS',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('generar_cupones_form'),
    'access arguments' => array('acceso a generar cupones'),
    'expanded' => TRUE,
  );//generar_cupones.inc
  $items['socios/adjuntar_foto'] = array(
    'title' => 'ADJUNTAR FOTO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('adjuntar_foto_form'),
    'access arguments' => array('acceso a adjuntar foto'),
    'expanded' => TRUE,
  );//adjuntar_foto.inc
  $items['socios/ingreso_socio'] = array(
    'title' => 'CONTROL DE INGRESO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ingreso_socio_form'),
    'access arguments' => array('acceso a ingreso socios'),
    'expanded' => TRUE,
  );//ingreso_socio.inc
  $items['socios/cobranza'] = array(
    'title' => 'COBRANZA',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cobranza_socio_buscar_form'),
    'access arguments' => array('acceso a gestion socio cobranza'),
    'expanded' => TRUE,
  );//cobranza_socio.inc
  $items['socios/plan_pago_socio'] = array(
    'title' => 'PLAN DE PAGO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plan_pago_socio_form'),
    'access arguments' => array('acceso a generar plan de pago de un socio'),
    'expanded' => TRUE,
  );//plan_pago_socio.inc
  $items['socios/registrar_pago/imprimir'] = array(
    'title' => 'RESUMEN DE PAGO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('imprimir_cuenta_socio_form'),
    'access arguments' => array('acceso a imprimir cuenta socio'),
    'expanded' => TRUE,
  );//imprimir_cuenta_socio.inc
  $items['socios/generar_liquidacion'] = array(
    'title' => 'LIQUIDACIÓN MENSUAL',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('generar_liquidacion_form'),
    'access arguments' => array('acceso a generar liquidacion mensual'),
    'expanded' => TRUE,
  );//generar_liquidacion.inc
  $items['socios/generar_liquidacion_ajax'] = array(
    'type' => MENU_CALLBACK,
     'page callback' => 'generar_liquidacion_callback',
     'access arguments' => array('access content'),
  );//imprimir_cuenta_socio.inc
  $items['socios/ingreso_socio/socio'] = array(
    'title' => 'INGRESO DE SOCIO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ingreso_socio_datos_socio_form'),
    'access arguments' => array('acceso a ingreso socio - socio'),
    'expanded' => TRUE,
  );
  $items['socios/recibos'] = array(
    'title' => 'RECIBOS DEL SOCIO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gestionar_recibos_form'),
    'access arguments' => array('acceso a recibos del socio'),
    'expanded' => TRUE,
  );//gestionar_recibos.inc
  $items['socios/anular_recibo'] = array(
    'title' => 'ANULAR RECIBO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('anular_recibo_form'),
    'access arguments' => array('acceso a anular recibo'),
    'expanded' => TRUE,
  );//gestionar_recibos.inc
  /*$items['socios/test'] = array(
    'title' => 'TEST',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('test_form'),
    'access arguments' => TRUE,
    'expanded' => TRUE,
  );//test.inc*/

  return $items;
}
?>
